from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from app.core.policy import ProviderPolicy
from app.domain.models import ForecastSnapshot, Location, NowcastPoint


class WeatherProvider(Protocol):
    def get_capabilities(self) -> dict[str, Any]: ...

    async def fetch_forecast(self, location: Location, requested_at: datetime) -> Any: ...

    async def fetch_current_conditions(self, location: Location) -> Any: ...

    def normalize_forecast(self, raw_response: Any) -> list[ForecastSnapshot]: ...

    def get_attribution(self) -> str: ...

    def get_policy(self) -> ProviderPolicy: ...


class ObservationProvider(Protocol):
    async def fetch_observations(
        self, location: Location, start_at: datetime, end_at: datetime
    ) -> Any: ...

    async def list_stations(self) -> Any: ...

    def select_reference_station(self, location: Location) -> Any: ...

    def normalize_observations(self, raw_response: Any) -> Any: ...


class NowcastProvider(Protocol):
    async def fetch_nowcast(self, location: Location, issued_at: datetime) -> Any: ...

    async def fetch_map_frames(self, bounds: Any, issued_at: datetime) -> Any: ...

    def normalize_nowcast(self, raw_response: Any) -> list[NowcastPoint]: ...

    def get_data_age(self) -> int: ...

